# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WIM.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(1200, 800))
        self.centralwidget.setMaximumSize(QtCore.QSize(1200, 800))
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 281, 801))
        self.widget.setObjectName("widget")
        self.imgListView = QtWidgets.QListView(self.widget)
        self.imgListView.setGeometry(QtCore.QRect(10, 70, 261, 711))
        self.imgListView.setObjectName("imgListView")
        self.targetLabel = QtWidgets.QLabel(self.widget)
        self.targetLabel.setGeometry(QtCore.QRect(10, 30, 71, 21))
        self.targetLabel.setObjectName("targetLabel")
        self.targetLineEdit = QtWidgets.QLineEdit(self.widget)
        self.targetLineEdit.setGeometry(QtCore.QRect(80, 30, 191, 21))
        self.targetLineEdit.setReadOnly(True)
        self.targetLineEdit.setObjectName("targetLineEdit")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(280, 0, 921, 801))
        self.tabWidget.setObjectName("tabWidget")
        self.cropTab = QtWidgets.QWidget()
        self.cropTab.setObjectName("cropTab")
        self.tabWidget.addTab(self.cropTab, "")
        self.flawRemoveTab = QtWidgets.QWidget()
        self.flawRemoveTab.setObjectName("flawRemoveTab")
        self.tabWidget.addTab(self.flawRemoveTab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.targetLabel.setText(_translate("MainWindow", "目标文件夹："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.cropTab), _translate("MainWindow", "裁剪"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flawRemoveTab), _translate("MainWindow", "瑕疵去除"))
